### ISSUE TITLE
Add compatible with This Plugin.

### ISSUE THREAD

**Issue by Master-Antonio** [pitaj/nodebb-plugin-calendar#10]
Hi.
I found this plugin https://community.nodebb.org/topic/2788/who-is-in-plugin .
it would be perfect if you add compatible with this plugin.

**Comment by btcmintus** [comment]
Any possibility of this getting an update for nodeBB 0.8.X ?

**Comment by pitaj** [comment]
I'm writing on other things right now, and will work on this when I have the time. I'd love to work on open source all the time, but between school and my freelancing, I just don't have the time.
