### ISSUE TITLE
No event triggered (it seems) from calender button in composition toolbar

### ISSUE THREAD

**Issue by Rimann91** [pitaj/nodebb-plugin-calendar#101]
I installed the plugin following instructions. Calendar tool button is there in the composition window. It says `edit_event` if you hover over it. However, when I click on this button nothing happens at all. I have restarted and rebuilt nodebb several times now with same results. On **Ubuntu 16.04 LTS** using *Chrome*.

**Comment by Rimann91** [comment]
Some more information and issues that may or may not be related to this not working. Changing anything in `/admin/plugins/calendar` will not save. According to instructions

> Configure permissions at ACP Manage > Categories page

There are no settings related to calender in '/admin/manage/categories' that I can see.

**Comment by pitaj** [comment]
The permissions were moved to ACP > Manage > Permissions.

As for the other issues:

- what version of NodeBB?
- what version of Node.js?
- what version of calendar plugin?
- any errors client side?
- any errors server side?

**Comment by Rimann91** [comment]
Nodebb v1.7.5
Node.js v6.11.5
unsure of calender version. Used `npm install nodebb-plugin-calendar@latest` to install
No errors client side or in server log

**Comment by Rimann91** [comment]
**UPDATE SOLUTION**
upgrading to nodebb v1.8.1 fixed this issue
