### ISSUE TITLE
Enable category permission for creating events by default

### ISSUE THREAD

**Issue by tom-rade** [pitaj/nodebb-plugin-calendar#109]
Enable category permission for creating events by default

**Comment by pitaj** [comment]
I don't think there's an easy way to do this. The only way I know of is listening for category creation events which _I'm_ not going to do.

I also don't see this as a particularly useful feature but if somebody really wants it they can send a PR or integrate it into a separate plugin for setting default privileges for new categories.

**Comment by tom-rade** [comment]
@pitaj I know many plugins such as the nodebb-plugin-poll which do this. So it shouldn't be that difficult. But ok.
