### ISSUE TITLE
Add option to disable "madatory"

### ISSUE THREAD

**Issue by tom-rade** [pitaj/nodebb-plugin-calendar#112]
Sending a reminder to all users that can vies the event? Our forum lets all users use the calendar. A single user could notify 10 000 users which is suboptimal to say the least.

Please add a global option to disable the mandatory function. Thanks.

**Comment by pitaj** [comment]
I'll add a permission for "can create mandatory events" on top of the existing "can create events" permission.

**Comment by pitaj** [comment]
Check out `nodebb-plugin-calendar@1.0.0-alpha.46`
