### ISSUE TITLE
Not loading on latest NodeBB Version

### ISSUE THREAD

**Issue by Starystars67** [pitaj/nodebb-plugin-calendar#114]
Hello, I am encountering an issue with your plugin on the latest version of NodeBB (1.11.2)
Please see the screenshot for any infomation i currently have:
![image](https://user-images.githubusercontent.com/15389482/53299317-3dec6900-3830-11e9-9c32-14bb5056df08.png)

How can i assist with resolving this further?

**Comment by pitaj** [comment]
What's your Nose.js version? Upgrade to the latest Node v10
