### ISSUE TITLE
$ in event description

### ISSUE THREAD

**Issue by sharked76** [pitaj/nodebb-plugin-calendar#119]
Hello

If you put a $ in the event description it breaks and displays gibberish, if you remove the $ then its fine.

With the $ in the description:
![image](https://user-images.githubusercontent.com/48071101/57867687-97c95300-77cf-11e9-9671-fcab3388e72c.png)

With the $ removed:
![image](https://user-images.githubusercontent.com/48071101/57867603-6d779580-77cf-11e9-8632-90d5d7bb23ad.png)

**Comment by pitaj** [comment]
Good catch, I'll have to see what I can do about this.

**Comment by sharked76** [comment]
Any eta on this?

**Comment by pitaj** [comment]
Sorry I haven't really had a good chance to sit down and really crank out some fixed for this repo. Maybe this weekend I'll have time.
