### ISSUE TITLE
If you enable email digest, the events show up as gibberish

### ISSUE THREAD

**Issue by sharked76** [pitaj/nodebb-plugin-calendar#120]
If you enable email digest, when you get the email, if you have an event they show up as gibberish.  I think this should be fixed or make events excluded from the email digest.

![image](https://user-images.githubusercontent.com/48071101/58194039-6d293f80-7c92-11e9-923b-c5b827be9979.png)

**Comment by sharked76** [comment]
Any eta on this?

**Comment by pitaj** [comment]
Having trouble reproducing this. This is what it looks like for me:
![image](https://user-images.githubusercontent.com/803701/60379109-137f0800-99ea-11e9-8472-94b5644d7ba0.png)

What version of the plugin and NodeBB on you on?

**Comment by pitaj** [comment]
Closed for inactivity
