### ISSUE TITLE
Calendar is just blank

### ISSUE THREAD

**Issue by sharked76** [pitaj/nodebb-plugin-calendar#126]
After updating NodeBB to 1.13.0 the calendar is now just showing blank:

![image](https://user-images.githubusercontent.com/48071101/70174835-a3b12f80-16a3-11ea-941e-a23cbc74604e.png)

**Comment by pitaj** [comment]
I'm pretty busy with other things but I'll try to get this updated for compatibility soon.

**Comment by sharked76** [comment]
Anything I can do to help speed up the fix? Donation for your time?

Duane
________________________________

**Comment by sharked76** [comment]
Hi Pitaj, just wondering if there is any way I can help speed up the fix on this? I don't mind donating for your time!

**Comment by pitaj** [comment]
nodebb-plugin-calendar@1.0.0-alpha.51
