### ISSUE TITLE
Unhandled Promise Rejection Warning

### ISSUE THREAD

**Issue by AliCihan** [pitaj/nodebb-plugin-calendar#128]
Hi Pitaj, I am not sure if anything is wrong, because there is no error in our usage of the plugin, but after upgrading to the latest version we kept having this kind of warnings in the log, FYI... 

(node:7116) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'repeats' of null
    at restoreEvent (/home/nodebb/nodebb/node_modules/nodebb-plugin-calendar/src/lib/event.js:43:25)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:7116) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 70)
(node:7116) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'repeats' of null
    at restoreEvent (/home/nodebb/nodebb/node_modules/nodebb-plugin-calendar/src/lib/event.js:43:25)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:7116) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 71)
(node:7116) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'repeats' of null
    at restoreEvent (/home/nodebb/nodebb/node_modules/nodebb-plugin-calendar/src/lib/event.js:43:25)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:7116) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 72)
(node:7116) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'repeats' of null
    at restoreEvent (/home/nodebb/nodebb/node_modules/nodebb-plugin-calendar/src/lib/event.js:43:25)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:7116) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 73)

**Comment by pitaj** [comment]
fixed in nodebb-plugin-calendar@1.0.0-alpha.55
