### ISSUE TITLE
Integration with Google Calendar

### ISSUE THREAD

**Issue by linuzo** [pitaj/nodebb-plugin-calendar#129]
How can I use this to integrate a google calendar where I post events to show in Nodebb calendar??

Is this feature implemented already??

**Comment by pitaj** [comment]
Do you mean having events from this calendar show up in your Google calendar, or having events in your Google calendar showing up in this calendar?

**Comment by linuzo** [comment]
Yep I want to implement events created in a google calendar into this calendar since we already create the events on google calendar. We would like to show those events to members on the nodebb community part of the site. 

Thanks for your help.

**Comment by pitaj** [comment]
Closing this in favor of #46
