### ISSUE TITLE
notification for repeating and mandatory events

### ISSUE THREAD

**Issue by AliCihan** [pitaj/nodebb-plugin-calendar#130]
this is how notification looks for a mandatory, repeating event (monthly):

![Screen Shot 2020-06-17 at 9 23 53 PM](https://user-images.githubusercontent.com/52054408/85079383-afbe9380-b194-11ea-968f-89e9a6ebb144.png)

it is the same for everyone, admins/event creator/normal users... 

and this is how it looks after clicking notification:

![Screen Shot 2020-06-17 at 9 24 24 PM](https://user-images.githubusercontent.com/52054408/85079464-e98f9a00-b194-11ea-906c-93fabc592a38.png)

**Comment by pitaj** [comment]
Hi, just wanted to let you know that I'm in the process of revamping the code so I can begin to address these issues.

**Comment by pitaj** [comment]
Should be fixed in 1.1.0
