### ISSUE TITLE
 The links do not work properly

### ISSUE THREAD

**Issue by roghaye-m** [pitaj/nodebb-plugin-calendar#134]
Events in the calendar are not linked to the Event topic.
When I click on the event on calender page , only the url changes and remains on the same calendar  page!
like this  : /calendar/event/1633395

**Comment by pitaj** [comment]
You should see a pop-up with the event. On that pop-up, you should see a button that will take you to the post.

I'm guessing you don't see any of that. Are there any errors in your browser console?

**Comment by roghaye-m** [comment]
yes there is some errors 
![image](https://user-images.githubusercontent.com/37838903/99457471-478cfd00-2940-11eb-84b3-50d16c933029.png)

when i refresh the events link , i see the pop-up 

how i can fix it?

**Comment by pitaj** [comment]
Please try `nodebb-plugin-calendar@1.0.0-alpha.56`. It should fix this issue.

**Comment by roghaye-m** [comment]
> Please try `nodebb-plugin-calendar@1.0.0-alpha.56`. It should fix this issue.


 I tried this but the result was the same as before, it needs to be refreshed to display the pop-up

**Comment by pitaj** [comment]
Did you rebuild and restart after installing it?

**Comment by roghaye-m** [comment]
> Did you rebuild and restart after installing it?

yes

**Comment by pitaj** [comment]
Is the error in the browser console the same? Can you try clearing your cache our using a different browser?

**Comment by roghaye-m** [comment]
The error is this :
![image](https://user-images.githubusercontent.com/37838903/101648402-04a9db00-3a4f-11eb-89af-150f2211f68d.png)

I try this version: 
that is the cn version, 
i could not find the normal version of 1.0.0-alpha.56
![image](https://user-images.githubusercontent.com/37838903/101648814-72ee9d80-3a4f-11eb-9b2c-2cb482e02403.png)


I changed my browser but nothing changed.

**Comment by pitaj** [comment]
That plugin is not made by me. I don't know who made it.

You'll need to run

    npm install nodebb-plugin-calendar@1.0.0-alpha.56

To install the new version.

**Comment by roghaye-m** [comment]
thank you  it works properly 👍
