### ISSUE TITLE
Clicking on Calendar Entry no longer works after upgrade to nodebb 16.2

### ISSUE THREAD

**Issue by sharked76** [pitaj/nodebb-plugin-calendar#136]
After updating nodebb to 1.16.2 when I click on any of my calendar entries, nothing happens, the event details overlay that used to pop up does not appear.  

When I click the calendar entry, the address bar changes to the event for example:
https://members.tirpc.ca/calendar/event/1757

But nothing happens other then the address bar changing.  If I put my cursor in the address bar and press Enter, then the event overlay appears.

**Comment by pitaj** [comment]
What version of the plugin are you on? Are there any errors in your browser JS console or in the NodeBB server logs?

**Comment by sharked76** [comment]
Its weird, as it says I have .55 and the latest is .52 ?
Nothing in the NodeBB server logs



nodebb-plugin-calendar

Calendar and events for NodeBB

Installed 1.0.0-alpha.55 | Latest 1.0.0-alpha.52


[cid:e6be4e58-ef57-4522-975e-99005a85cf80]

________________________________

**Comment by pitaj** [comment]
What about in the JS console in your browser developer tools?

**Comment by sharked76** [comment]
Is this what you mean?


[cid:ad7327e6-18a0-4ed5-880f-97752415af1b]





________________________________

**Comment by pitaj** [comment]
Your image isn't showing up. Could you upload the image through the GitHub interface instead of email?

**Comment by sharked76** [comment]
![image](https://user-images.githubusercontent.com/48071101/106364496-77239280-62fd-11eb-9f0c-8a821bf7b343.png)

**Comment by pitaj** [comment]
This is the same issue as #134 

You'll need to upgrade to `nodebb-plugin-calendar@1.0.0-alpha.56`. You can do it manually like so:
```
npm install nodebb-plugin-calendar@1.0.0-alpha.56
```

I'm not sure why it isn't showing up as an available upgrade in your ACP.

**Comment by sharked76** [comment]
Hi, I tried running:
npm install nodebb-plugin-calendar@1.0.0-alpha.56

And I rebuild/restarted NodeBB
Still shows this in the ACP:

![image](https://user-images.githubusercontent.com/48071101/106365171-c79cef00-6301-11eb-8342-7efcb11396ab.png)

**Comment by pitaj** [comment]
Where did you run the command? It needs to be run in the nodebb directory.

**Comment by sharked76** [comment]
Thanks, I should have known that, I thought npm was systemwide
After running npm install nodebb-plugin-calendar@1.0.0-alpha.56 inside the nodebb directory its now working!
