### ISSUE TITLE
Unable to Edit events after updating to NodeBB 1.16.2

### ISSUE THREAD

**Issue by sharked76** [pitaj/nodebb-plugin-calendar#137]
Now, that I have updated to 1.16.2, I am unable to edit any events in my calendar, when I click on edit post, it shows the event as being invalid for example:

[event-invalid][name]Bullseye Shoot[/name][allday]false[/allday][startDate]1616331600000[/startDate][endDate]1616342400000[/endDate][reminders][][/reminders][location]Indoor Range[/location][description]Bullseye Shoot[/description][mandatory]false[/mandatory][/event-invalid]

The event is still showing up in the calendar correctly, even though when trying to edit it, it says its invalid

If I delete the post and recreate the event I am then able to edit it without issue.

It would seem that any events that were created prior to upgrading to 1.16.2 are now unable to edit.

**Comment by pitaj** [comment]
What version of the plugin are you on?

**Comment by sharked76** [comment]
It doesn't show me anything newer to update:

![image](https://user-images.githubusercontent.com/48071101/108251629-a1f74e80-7125-11eb-9c17-d8042d30c19b.png)

**Comment by pitaj** [comment]
Please try 1.0.0-alpha.57

    npm install nodebb-plugin-calendar@1.0.0-alpha.57

**Comment by sharked76** [comment]
Hi, I ran the command what you said, however it giving lots of warnings:

npm WARN @apidevtools/swagger-parser@10.0.2 requires a peer of openapi-types@>=7 but none is installed. You must install peer dependencies yourself.
npm WARN nodebb-plugin-emoji-android@2.0.0 requires a peer of nodebb-plugin-emoji@^2.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN textcomplete.contenteditable@0.1.1 requires a peer of textcomplete@^0.14.2 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/fullcalendar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/fullcalendar/node_modules/watchpack/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

+ nodebb-plugin-calendar@1.0.0-alpha.57
updated 1 package and audited 1460 packages in 19.008s

96 packages are looking for funding
  run `npm fund` for details

found 1 moderate severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details

**Comment by pitaj** [comment]
And after running that and doing a rebuild and restart, did it resolve the issue?
