### ISSUE TITLE
Repeating events no longer work

### ISSUE THREAD

**Issue by sharked76** [pitaj/nodebb-plugin-calendar#138]
Since updating to NodeBB 1.16.2 and Calendar Alpha .57 when you select the options for repeating calendar event, they don't actually do anything, the calendar does not show the event repeating correctly:

![image](https://user-images.githubusercontent.com/48071101/110553488-085d0480-8107-11eb-902d-37833e1984dd.png)

![image](https://user-images.githubusercontent.com/48071101/110553529-1dd22e80-8107-11eb-8b77-d2f60c04f682.png)

Existing repeating events that I had already in place prior to NodeBB 1.16.2 and Calendar Alpha .57 still show up in the calendar correctly, but any new repeating events that I create do not work.

**Comment by pitaj** [comment]
I have been working on a big upgrade that should fix done of these issues. I want to support this but I don't have a ton of free time lately.

**Comment by pitaj** [comment]
Please try version 1.1.0

I didn't reproduce this issue on 1.16.2, but it shouldn't happen with the latest version.
