### ISSUE TITLE
Icon gone since update 1.1.0 and event problem display

### ISSUE THREAD

**Issue by aworobel** [pitaj/nodebb-plugin-calendar#139]
Hello,

I have a bug since i did the upgrade in 1.1.0 (from alpha57).
Indeed i have no icon calendar when i post. Tried to reinstall with npm *@latest
Other problem : in events already posted, i have this strange display (see screen below).

Tried to rebuild nodebb, restart, nothing better.
Thanks in advance for your help.

Arnaud.
[
![screen](https://user-images.githubusercontent.com/12534464/111283214-2c58a280-863f-11eb-80a5-283e42aaedf0.png)
](url)

**Comment by pitaj** [comment]
Do you have any errors in the logs? What version of Node are you on?

**Comment by aworobel** [comment]
Hello,
I am in v1.16.2

I see this error in developer tools mode (from web nav) related to the plugin path :

```
Uncaught (in promise) TypeError: s.locale is not a function
    at clientSideTranslation.ts:27

```

**Comment by pitaj** [comment]
What language do you have selected in user settings?

**Comment by aworobel** [comment]
Sorry, incomplete information :)
The forum is in french and in my user settings language is : French (France) (fr)

Thanks.

**Comment by pitaj** [comment]
I was able to reproduce this by changing my language to French, it does not happen on en-US. You have to do a hard refresh of the page in order to fully apply the language setting.

I'm working on a fix.

**Comment by aworobel** [comment]
Thanks a lot.
Indeed there was a cache effect during my test.


Arnaud.

Le mar. 16 mars 2021 à 17:58, Peter Jaszkowiak ***@***.***> a
écrit :
