### ISSUE TITLE
Install via NodeBB Admin UI does not work

### ISSUE THREAD

**Issue by altembo** [pitaj/nodebb-plugin-calendar#14]
Hi,

after installing your plugin through the admin ui -> plugins it is not possible to access the calendar.
Accessing your plugins settings from admin ui result in "site not found" errors. (*/admin/plugins/calendar and */calendar),

Reloading and restarting NodeBB from Admin UI did not help.

Any suggestions? I am running NodeBB on OpenStack.

Kind Regards,
Aleks

**Comment by altembo** [comment]
Installing the plugin right from the source and restarting my NodeBB App solved the Issue.

[Guide (post 10)](https://community.nodebb.org/topic/4401/nodebb-plugin-calendar-fully-featured-calendar-plugin-for-nodebb-testers-needed/9): 

1. Open a command window in the NodeBB directory
2. Navigate to the node_modules directory (cd node_modules) and run npm remove nodebb-plugin-calendar
3. Delete the nodebb-plugin-calendar directory with del nodebb-plugin-calendar or rm -r nodebb-plugin-calendar
4. Clone the master branch of the git repository git clone https://github.com/pitaj/nodebb-plugin-calendar
5. Navigate to the nodebb-plugin-calendar directory with cd nodebb-plugin-calendar
6. Install npm dependencies with the command npm install
Those commands should install it correctly. It should then be visible in the ACP (maybe after a restart) to be activated.

**Comment by pitaj** [comment]
Installing the newest version from the ACP isn't supported yet. I have not
pushed the latest to NPM, the repository which the ACP install makes use
of.

For now, please just install it like you did. I'm still ironing out a few
bugs, after which I will publish v0.2.0 to NPM.

**Comment by altembo** [comment]
Yeah no problem, I just copied it for others coming across  ;-)
