### ISSUE TITLE
Firehook is not a function since v.1.18.2 upgrade

### ISSUE THREAD

**Issue by aworobel** [pitaj/nodebb-plugin-calendar#145]
Hello,

Seems to be a bug (deprecate maybe) since version 18.1.2 with firehook when we go to the calendar : www.onekite.com/calendar
It does not show the events and popup "firehook is not a function" instead.

Here is the full debug. Thanks :)

Sep 10 16:18:03 web nodebb[757]: 2021-09-10T14:18:03.849Z [4500/814] - #033[3
error#033[39m: plugins.calendar.getEventsByDate
Sep 10 16:18:03 web nodebb[757]: TypeError: fireHook is not a function
Sep 10 16:18:03 web nodebb[757]:     at Object.escapeEvent (/opt/nodebb/node_
dules/nodebb-plugin-calendar/src/lib/event.ts:214:5)
Sep 10 16:18:03 web nodebb[757]:     at /opt/nodebb/node_modules/nodebb-plugi
calendar/src/lib/sockets.ts:135:9
Sep 10 16:18:03 web nodebb[757]:     at Array.map (<anonymous>)
Sep 10 16:18:03 web nodebb[757]:     at getEventsByDateSocket (/opt/nodebb/no
_modules/nodebb-plugin-calendar/src/lib/sockets.ts:130:16)
Sep 10 16:18:03 web nodebb[757]:     at processTicksAndRejections (internal/p
cess/task_queues.js:95:5)
p 10 16:18:03 web nodebb[757]:     at onMessage (/opt/nodebb/src/socket.io/
dex.js:164:19)

**Comment by pitaj** [comment]
v1.1.3
