### ISSUE TITLE
NodeBB 1.19.0 - "fireHook is not a function" error

### ISSUE THREAD

**Issue by ylothar** [pitaj/nodebb-plugin-calendar#147]
![Schermata da 2022-01-15 12-40-50](https://user-images.githubusercontent.com/682247/149620497-607d6ea5-c512-4e54-a19e-4c59e0cc8a6f.png)

Activated this plugin for the first time on my just updated NodeBB v.1.19.0 and when I try to add an event to a new topic I get this error and the post in not saved.

**Comment by pitaj** [comment]
What version of the plugin are you on?

**Comment by evtifiev** [comment]
@ylothar you need to run `npm install nodebb-plugin-calendar@latest` and rebuild NodeBB `./nodebb build`. Apparently you have a version from the store (1.0.0-alpha.52), and the latest version is (1.1.3). This solved my issue.

**Comment by ylothar** [comment]
@evtifiev thank you, it worked!
