### ISSUE TITLE
translations disappear (admin)

### ISSUE THREAD

**Issue by codejanovic** [pitaj/nodebb-plugin-calendar#17]
translations randomly disappear in admin console.
I could trigger that issue with refreshing the admin console with CTRL+F5

system:
- NodeBB on OpenShift
- Google Chrome
- latest Calendar from Master + german translations from #15 

![image](https://cloud.githubusercontent.com/assets/7228633/7785933/30877386-01ac-11e5-8eda-6a05294120cc.png)

**Comment by pitaj** [comment]
Same cause as #18, your websockets don't work, so the translations don't work.

**Comment by pitaj** [comment]
Was this fixed when you fixed the websocket issues?

**Comment by altembo** [comment]
Nope, Issue still exists. After pressing CTRL+F5 translations disappear again. But unlike before, after simply reentering calendar-admin the translation can be loaded again and works fine.

**Comment by pitaj** [comment]
This is a problem with NodeBB core, not with my plugin. Regardless, I'll
see what is causing it and send them a PR with a did as soon as I can.

**Comment by pitaj** [comment]
I'm unable to reproduce this issue. What version of NodeBB are you on?

**Comment by altembo** [comment]
I am on 1.6.X
