### ISSUE TITLE
gridview (days) missing

### ISSUE THREAD

**Issue by codejanovic** [pitaj/nodebb-plugin-calendar#18]
I guess there should be some kind of gridview with the day of month when opening the calendar.
At the moment it looks like this for me:
![image](https://cloud.githubusercontent.com/assets/7228633/7785937/c104d0e8-01ac-11e5-8a3d-5e8ac45004e4.png)

**Comment by pitaj** [comment]
Your websockets aren't working: 

![screenshot 79](https://cloud.githubusercontent.com/assets/803701/7786359/d8661648-0184-11e5-80a0-7fd61ab711a9.png)

**Comment by altembo** [comment]
Thanks for clearing this up, I am having a look at this.

**Comment by altembo** [comment]
So I had to add sockets.io settings to my config.json to get websockets to work ([link](https://community.nodebb.org/topic/3703/solved-socket-io-websocket-custom-port)):

"socket.io": {
    "address": "http://myforum.com:8000"
}

But the Issues still exist (now, without the websocket errors). May you have a look again into this? :-(

**Comment by pitaj** [comment]
Now there's an issue with moment. I'm not able to repro right now, but I'll keep trying.
