### ISSUE TITLE
translation missing edit-view (add event)

### ISSUE THREAD

**Issue by codejanovic** [pitaj/nodebb-plugin-calendar#19]
translations for "event_name" and "place" are missing in german translation.
I checked the translation json twice, but could not find any syntax mistake.

![image](https://cloud.githubusercontent.com/assets/7228633/7785945/2f0b4c48-01ad-11e5-8987-313bf09afefc.png)

**Comment by altembo** [comment]
Are you able to reproduce this on your side?

**Comment by pitaj** [comment]
Haven't been able to yet, but I'll try again. Been pretty busy lately.

**Comment by altembo** [comment]
Okay, theres no need to hurry as I am just testing around with NodeBB ;-) Ping me if theres something I can do for you.

**Comment by pitaj** [comment]
I can't reproduce this. I think there may be an issue on your side.

**Comment by altembo** [comment]
Ye, I see :P I am going to reinstall NodeBB with the latest version and head back again
