### ISSUE TITLE
Update route for plugin admin panel

### ISSUE THREAD

**Issue by frenchja** [pitaj/nodebb-plugin-calendar#20]
The current route, `https://domain.com/admin/plugins/calendar`, doesn't render an admin page.  

@barisusakli had a similar error message with the API route: https://github.com/NodeBB/nodebb-widget-essentials/commit/f72ffa0f86c1afe1ccc7ade7a2c0e8398442d068

**Comment by frenchja** [comment]
Calendar: 0.1.1
NodeBB: a5b8a656e9e896bfaaa093c25aa5ec99c0e5b6ad

**Comment by pitaj** [comment]
Issue has same source as #21
