### ISSUE TITLE
Adding route breaks CSS layout

### ISSUE THREAD

**Issue by frenchja** [pitaj/nodebb-plugin-calendar#21]
Adding the `/calendar` route to `admin/general/navigation` in the ACP breaks the CSS of the top nav bar in persona.

NodeBB 0.7.0
Persona 0.1.56

**Comment by pitaj** [comment]
Will investigate. It *was* working just fine. 

What commit of NodeBB and this plugin are you on?

**Comment by frenchja** [comment]
Calendar: 0.1.1
NodeBB: a5b8a656e9e896bfaaa093c25aa5ec99c0e5b6ad

**Comment by pitaj** [comment]
@frenchja 
> Calendar: 0.1.1

Well, that's your problem. You're on an old version. The latest npm version (the one from the ACP) doesn't support NodeBB versions `>0.5.6`. You need to follow the install from git instructions in the readme.

**Comment by frenchja** [comment]
:+1:
