### ISSUE TITLE
Groups do not persist after save changes

### ISSUE THREAD

**Issue by frenchja** [pitaj/nodebb-plugin-calendar#22]
![screen shot 2015-05-28 at 8 17 13 pm](https://cloud.githubusercontent.com/assets/720035/7874609/5e404fea-0577-11e5-9a86-4a23f6657460.png)
![screen shot 2015-05-28 at 8 18 16 pm](https://cloud.githubusercontent.com/assets/720035/7874610/5facaa4a-0577-11e5-8140-401984a2d9ea.png)

**Comment by Prior99** [comment]
+1

**Comment by jenkin** [comment]
I have the same problem (v0.8.2), here the errors on chrome console when the "Save changes" button is clicked:

"""
nodebb.min.js?v=b05a1521-13f7-4209-9c2e-6e16b7afcb67:3 POST http://[host]/api/admin/plugins/calendar/save net::ERR_CONNECTION_REFUSED

w.ajaxTransport.n.send @ nodebb.min.js?v=b05a1521-13f7-4209-9c2e-6e16b7afcb67:3
w.extend.ajax @ nodebb.min.js?v=b05a1521-13f7-4209-9c2e-6e16b7afcb67:3
w.each.w.(anonymous function) @ nodebb.min.js?v=b05a1521-13f7-4209-9c2e-6e16b7afcb67:3(anonymous function) @ VM3821:3
w.event.dispatch @ nodebb.min.js?v=b05a1521-13f7-4209-9c2e-6e16b7afcb67:2
$event.dispatch @ jquery.event.drag.js?v=b05a1521-13f7-4209-9c2e-6e16b7afcb67:374
w.event.add.y.handle @ nodebb.min.js?v=b05a1521-13f7-4209-9c2e-6e16b7afcb67:2

nodebb.min.js?v=b05a1521-13f7-4209-9c2e-6e16b7afcb67:5 GET http://10.1.10.6:4567/socket.io/?EIO=3&transport=polling&t=1442828203570-11 net::ERR_CONNECTION_REFUSED

s.17.l.create @ nodebb.min.js?v=b05a1521-13f7-4209-9c2e-6e16b7afcb67:5
l @ nodebb.min.js?v=b05a1521-13f7-4209-9c2e-6e16b7afcb67:4
s.17.c.request @ nodebb.min.js?v=b05a1521-13f7-4209-9c2e-6e16b7afcb67:4
s.17.c.doPoll @ nodebb.min.js?v=b05a1521-13f7-4209-9c2e-6e16b7afcb67:4
s.18.c.poll @ nodebb.min.js?v=b05a1521-13f7-4209-9c2e-6e16b7afcb67:5
s.18.c.doOpen @ nodebb.min.js?v=b05a1521-13f7-4209-9c2e-6e16b7afcb67:5
s.14.o.open @ nodebb.min.js?v=b05a1521-13f7-4209-9c2e-6e16b7afcb67:4
s.13.p.open @ nodebb.min.js?v=b05a1521-13f7-4209-9c2e-6e16b7afcb67:4
p @ nodebb.min.js?v=b05a1521-13f7-4209-9c2e-6e16b7afcb67:4
p @ nodebb.min.js?v=b05a1521-13f7-4209-9c2e-6e16b7afcb67:4
s.3.h.open.h.connect @ nodebb.min.js?v=b05a1521-13f7-4209-9c2e-6e16b7afcb67:4
(anonymous function) @ nodebb.min.js?v=b05a1521-13f7-4209-9c2e-6e16b7afcb67:4

nodebb.min.js?v=b05a1521-13f7-4209-9c2e-6e16b7afcb67:5 GET http://10.1.10.6:4567/socket.io/?EIO=3&transport=polling&t=1442828205071-12 net::ERR_CONNECTION_REFUSED

s.17.l.create @ nodebb.min.js?v=b05a1521-13f7-4209-9c2e-6e16b7afcb67:5
l @ nodebb.min.js?v=b05a1521-13f7-4209-9c2e-6e16b7afcb67:4
s.17.c.request @ nodebb.min.js?v=b05a1521-13f7-4209-9c2e-6e16b7afcb67:4
s.17.c.doPoll @ nodebb.min.js?v=b05a1521-13f7-4209-9c2e-6e16b7afcb67:4
s.18.c.poll @ nodebb.min.js?v=b05a1521-13f7-4209-9c2e-6e16b7afcb67:5
s.18.c.doOpen @ nodebb.min.js?v=b05a1521-13f7-4209-9c2e-6e16b7afcb67:5
s.14.o.open @ nodebb.min.js?v=b05a1521-13f7-4209-9c2e-6e16b7afcb67:4
s.13.p.open @ nodebb.min.js?v=b05a1521-13f7-4209-9c2e-6e16b7afcb67:4
p @ nodebb.min.js?v=b05a1521-13f7-4209-9c2e-6e16b7afcb67:4
p @ nodebb.min.js?v=b05a1521-13f7-4209-9c2e-6e16b7afcb67:4
s.3.h.open.h.connect @ nodebb.min.js?v=b05a1521-13f7-4209-9c2e-6e16b7afcb67:4
(anonymous function) @ nodebb.min.js?v=b05a1521-13f7-4209-9c2e-6e16b7afcb67:4
"""
