### ISSUE TITLE
Unable to use configuration page, calendar not in header

### ISSUE THREAD

**Issue by Phattie** [pitaj/nodebb-plugin-calendar#23]
I'm using NodeBB 0.7.0 on Node v0.10.25 with Calendar 0.2.0 and I'm getting the following when trying to use the Calendar configuration page:

https://i.imgur.com/Zj0j9WI.png

When starting NodeBB using the dev argument, the only mention of calendar is as follows:

29/5 01:29 [15982] - warn: [plugins/nodebb-plugin-calendar] This plugin may not be compatible with your version of NodeBB. This may cause unintended behaviour or crashing.
29/5 01:29 [15982] - warn: [plugins/nodebb-plugin-calendar] In the event of an unresponsive NodeBB caused by this plugin, run ./nodebb reset plugin="nodebb-plugin-calendar".

29/5 01:29 [15982] - verbose: [plugins] Loaded plugin: nodebb-plugin-calendar

Any ideas?

**Comment by Phattie** [comment]
OK so inexplicably the configuration window is now functioning correctly with no changes made, however the calendar itself is not showing up anywhere.

**Comment by pitaj** [comment]
Yes, the header icon has to be manually added to the header after install. This is how the new system works, (Since 0.7.0) and I don't think overriding it would be helpful. I do need to update some things related to the icon, but everything else should be fine.
