### ISSUE TITLE
Uncaught TypeError: b.locale is not a function

### ISSUE THREAD

**Issue by Radiergummi** [pitaj/nodebb-plugin-calendar#24]
Day view missing.. Ideas?

![bildschirmfoto 2015-06-03 um 22 43 44](https://cloud.githubusercontent.com/assets/6115429/7970993/07e5fd8c-0a42-11e5-9f56-59043f7cc9e0.png)

**Comment by pitaj** [comment]
Can you try the latest commit (872d6eaff67e90c36fa2cec9f923abd0bf3eabcb) and see if that resolves this?

**Comment by pitaj** [comment]
Is this on a public server I can access and troubleshoot? I'm unable to reproduce.

**Comment by Radiergummi** [comment]
Just pulled, am on `6f0d630` now. Error message has changed, but the calendar still doesn't work...
```
Uncaught TypeError: Cannot read property 'fn' of undefined(anonymous function) @ k.execCb @ nodebb.min.js?1c690ba2:12_.check @ nodebb.min.js?1c690ba2:12(anonymous function) @ nodebb.min.js?1c690ba2:12t @ nodebb.min.js?1c690ba2:12(anonymous function) @ nodebb.min.js?1c690ba2:12z @ nodebb.min.js?1c690ba2:12_.emit @ nodebb.min.js?1c690ba2:12_.check @ nodebb.min.js?1c690ba2:12_.enable @ nodebb.min.js?1c690ba2:12_.init @ nodebb.min.js?1c690ba2:12g @ nodebb.min.js?1c690ba2:12k.completeLoad @ nodebb.min.js?1c690ba2:12k.onScriptLoad @ nodebb.min.js?1c690ba2:12
```


It is on a public server: (https://schreibnacht.de/calendar)

**Comment by pitaj** [comment]
Alright I pushed another commit 029a6a2d4398e59a7f149cb46912a06b5b25f7a8

Try that.

**Comment by Radiergummi** [comment]
Just removed it completely and pulled again, get the initial error again. If I can provide you with logfiles etc, I'll happily do so.

**Comment by Radiergummi** [comment]
@pitaj , sorry to annoy you with it, but any updates on this?

**Comment by pitaj** [comment]
I have no idea what is causing this. Everything works perfectly on my local
install. I can't reproduce this issue.

What browser are you using?
What version of NodeBB?
Are you on the master branch of n-p-c?

**Comment by Radiergummi** [comment]
I can reproduce with Firefox and Chrome, have 0.7.0 running and I am on master, yes...

**Comment by michelpeters** [comment]
I had the same issue. I figured the "locale" had to do with the MomentJS dependency and opened the source to see what actually went wrong. It told me that "moment.locale" could not be found. I had MomentJS loaded, but still couldn't get it to work. 

If you also have an existing MorrisJS included, the solution might be to get the most recent MorrisJS version from JS and replace your existing one. This solved it for me.

**Comment by favour121** [comment]
Same issue.

**Comment by favour121** [comment]
Update Moment.JS

**Comment by pitaj** [comment]
Yeah I'm not really supporting this plugin right now. Gonna work on it over brea
