### ISSUE TITLE
Still in work?

### ISSUE THREAD

**Issue by BlackStonedLover** [pitaj/nodebb-plugin-calendar#29]
It doesnt shown up in the ACP and I would like to have a Calendar in my Forum any updates in future?

**Comment by pitaj** [comment]
Yes I'm still in the process of rewriting this.

**Comment by BlackStonedLover** [comment]
Very nice :) Thanks a lot <3

**Comment by Anakior** [comment]
Any update on the advancement? I have to say that i'm looking forward to see it working again. :+1:

**Comment by pitaj** [comment]
I haven't been able to work on this much because I'm still very busy with
school. But come late may, this will be my main focus.

**Comment by huegelc** [comment]
I´m also very interested in this plugin! :+1:  Hope that you find time to continue working on this

**Comment by gnucoder** [comment]
Hello, 

Is this working with NodeBB v1.0.3 ? Is it planned ? It's the only missing feature for my forum :)

Tks a lot.

**Comment by sunsetbrew** [comment]
I am looking forward to this as well.
