### ISSUE TITLE
Requirements?

### ISSUE THREAD

**Issue by huegelc** [pitaj/nodebb-plugin-calendar#30]
What nodebb requirements has the plugin?

**Comment by huegelc** [comment]
Is this plugin dead?

**Comment by pitaj** [comment]
The plugin isn't dead. I'm in the middle of refactoring it. Should be done
within a month or so.

**Comment by huegelc** [comment]
Thank you! Much appreciated. :+1:

**Comment by huegelc** [comment]
I think this would be a very important plugin for the most nodebb users. I'll be glad to make a donation.

**Comment by pitaj** [comment]
Save your money until I'm done.
