### ISSUE TITLE
Nodebb 1.0.3 compatibility and "Feature Request "

### ISSUE THREAD

**Issue by gnucoder** [pitaj/nodebb-plugin-calendar#31]
Hi,

I would like to send my letter to Santa Claus ^^ Here is what I want for the next update: 
- [x] NodeBB 1.0.3 compatibility.
- [x] Event creation by members.
- [x] RSVP system (Yes, Maybe, No).
- [x] Ability to subscribe and unsubscribe from an event.
- [ ] Ability to set a max # of attendees permitted for each event.
- [x] Display a list of attendees.

Nice to have
- [ ] Waiting list management.

Thanks :)

**Comment by gdjam** [comment]
cool ~ it sounds great !!!

**Comment by joetm** [comment]
Yeah, it doesn't seem to work with my node installation (1.0.3). There are no settings in the admin area. Calendar is nowhere to be found after activation of the plugin.

**Comment by pitaj** [comment]
@joetm yeah this plugin is still a WIP for the latest versions of NodeBB.

@gnucoder how would you like the RSVP system to work? I think combining RSVP with subscription would be the simplest system. A *no* or no response at all would unsubscribe you, whereas a *maybe* or *yes* would subscribe you to the notifications for the event. Does that sound alright?

**Comment by gnucoder** [comment]
Thanks @pitaj I'm not sure to understand everything, but basically, Yes for notifications to be enabled / disabled automatically based on the answer (Yes, Maybe, No answer)... Good idea.  But it doesn't replace the RSVP system it self (showing the attendees list, ability to self subscribe / unsubscribe, etc...) Right? 

Thanks again for you support :)

**Comment by pitaj** [comment]
@gnucoder The idea is that there is an RSVP system where users can respond to the event (yes, no, maybe) and that shows a list of users for each response. Then, the RSVP system is used to dictate what users are subscribed to reminder notifications.  A *yes* gets all reminders, and a notification when the event starts. A *maybe* only gets a reminder when an event starts. A *no*, or no response, gets no reminders.

**Comment by gnucoder** [comment]
@pitaj sounds great to me. The 'Maybe' should papers receive a remember (not all) to encourage them to subscribe. A like that, thanks again :)

**Comment by pitaj** [comment]
@gnucoder @joetm @gdjam @BlackStonedLover @huegelc

This is an announcement of 
# nodebb-plugin-calendar v1.0.0-alpha.x

[Here's a link to the announcement and discussion on the NodeBB community forums](https://community.nodebb.org/post/52545)

Installation:

1. `npm install nodebb-plugin-calendar@latest`
2. Activate plugin in ACP
3. Configure category permissions in the ACP Manage > Categories area

**Comment by ralic** [comment]
It seems not working well with material theme... I was selecting en_US as the language.

20/7 00:51 [1894] - warn: [plugins/nodebb-plugin-calendar] Mapped path 'moment-locales => /Users/raliclo/work/npu/ticketscheduler/newTHAA/node_modules/nodebb-plugin-calendar/node_modules/moment/locale/' not found.
20/7 00:51 [1894] - warn: [plugins/nodebb-plugin-calendar] Mapped path 'fc-langs => /Users/raliclo/work/npu/ticketscheduler/newTHAA/node_modules/nodebb-plugin-calendar/node_modules/fullcalendar/dist/lang/' not found.

**Comment by pitaj** [comment]
Everything left for the todos is separately tracked now
