### ISSUE TITLE
1.0.0-alpha.1: Could not compile nodebb.min.js

### ISSUE THREAD

**Issue by frissdiegurke** [pitaj/nodebb-plugin-calendar#32]
When using non-dev NodeBB start, I get the following error:
```
19/7 06:26 [3839] - error: [meta/js] Could not compile nodebb.min.js: Unexpected token: operator (>)
19/7 06:26 [3839] - error:  Error: Unexpected token: operator (>)
```
I assume, it's some ES6 problems with NodeBB minification.

**Comment by pitaj** [comment]
Can you look at your local client.js and calendar.js in the build directory? They shouldn't have ES6 code but if they do my build is messed up.

**Comment by frissdiegurke** [comment]
They both do contain ES6
