### ISSUE TITLE
Voting results not shown in-post

### ISSUE THREAD

**Issue by frissdiegurke** [pitaj/nodebb-plugin-calendar#35]
Within the in-post panel of events, the users are not displayed within the voting results. They're shown properly within the dialog of the calendar route.

**Comment by frissdiegurke** [comment]
It seems to be hidden by
*/js-enabled.css*
```
[component="post/content"] img:not(.not-responsive):not([data-state]) {
	display: none !important;
}
```

**Comment by pitaj** [comment]
What theme & NodeBB version?

**Comment by frissdiegurke** [comment]
NodeBB `1.1.0`
Persona `4.1.7`

You can check [here](https://pai.frissdiegurke.com/topic/10/fachgruppentreffen-2016-07-21).
