### ISSUE TITLE
Date on mobile device

### ISSUE THREAD

**Issue by mtouriq** [pitaj/nodebb-plugin-calendar#51]
Hi, on my iphone it shows "hover for UTC date". Well, you cant hover on mobile right? :)
https://postimg.org/image/kgvigum0n/

**Comment by pitaj** [comment]
Hmmm. That shouldn't be happening. It should show the date in your local time.

What version of NodeBB, nodebb-plugin-calendar, and iOS are you on?

**Comment by mtouriq** [comment]
Hi pitaj,

Thanks for your reply

This is the data that you need:
NodeBB v1.1.0
Calendar Plugin 1.0.0-alpha.8
iPhone 6, OS 9.3.4

Please have a look at the attachments
Thank you
















——
Muchsin Assegaf

**Comment by pitaj** [comment]
@mtouriq Unfortunately attachments don't work with Github. You can email them directly to me if you need to, though.

**Comment by pitaj** [comment]
Unable to reproduce
