### ISSUE TITLE
Incompatible with NodeBB 1.1.3

### ISSUE THREAD

**Issue by gnimmelf** [pitaj/nodebb-plugin-calendar#58]
NodeBB Hash 7d1bbaa42d15579583179de614c8f25c3bbd37e1

Could not get it up and running, seems dev output finally hanged on compiling LESS/SASS.

Any more info I get help with on this?

Cheers!

**Comment by pitaj** [comment]
What version of the plugin is installed?

**Comment by gnimmelf** [comment]
Hm, removed it now, but first I tried installing via the ACP Plugin interface, then I just tried `npm install nodebb-plugin-calendar@latest` on top of that....

What way is recomended?

**Comment by pitaj** [comment]
Try 

    npm rm nodebb-plugin-calendar
    npm install nodebb-plugin-calendar@v1.0.0-alpha.7

In the terminal.

**Comment by gnimmelf** [comment]
ACP says: Installed 1.0.0-alpha.7 | Latest 1.0.0-alpha.8

Server started w/ `./nodebb dev`, on rebooting from ACP, it stutters along with a few :
```
14/9 19:02 [24848] - verbose: [meta/css] Minifying LESS/CSS
[cluster] Child Process (24848) has exited (code: null, signal: SIGKILL)
[cluster] Spinning up another process...
...
14/9 19:02 [24848] - verbose: [meta/css] Minifying LESS/CSS
[cluster] Child Process (24848) has exited (code: null, signal: SIGKILL)
[cluster] Spinning up another process...
...
14/9 19:03 [24883] - verbose: [meta/js] Minifying nodebb.min.js 
[Complete hang here...]
```

**Comment by pitaj** [comment]
What version of Node do you have?

**Comment by gnimmelf** [comment]
Node 'v4.5.0'

**Comment by pitaj** [comment]
Hmmm. Give me some time to check up on this.

**Comment by gnimmelf** [comment]
No stress. Wish I could be of more help =)

**Comment by pitaj** [comment]
Latest version is compatible with latest master NodeBB.
