### ISSUE TITLE
Not working after fresh install

### ISSUE THREAD

**Issue by JSteunou** [pitaj/nodebb-plugin-calendar#61]
I cannot figure out what's wrong. I'm with a fresh install of latest nodebb to make a new forum, installed a few plugin including this one, set the right to post events from the ACP in all categories for registered users, but the calendar button does nothing. I'm in the the post creation view, tested chrome & firefox, no error in the console, no error in the log, but the button just does nothing :/

**Comment by pitaj** [comment]
What version of NodeBB? What version of the calendar plugin? What browser? No errors in the browser console? No errors in the NodeBB log or with `./nodebb dev`?

Is this up on a public site that I can use to debug?

**Comment by JSteunou** [comment]
Like I said, last version, so

* nodebb branch 1.x.x fresh update
* plugin calendar alpha 8

and like I said firefox (49) and chromium (52) and not error in browser nor nodebb log.

I did not know about dev mode. Got nothing but 

```
5/10 19:45 [21836] - warn: [plugins/nodebb-plugin-calendar] Hook `filter:post.save` is deprecated, please use `filter:post.create` instead.
```

**Comment by JSteunou** [comment]
I'm clearly missing something... I tried a new fresh install on my pc, using redis, no password, dead simple installation (git clone, npm install, ...). Same issue...

**Comment by pitaj** [comment]
I'll look into this soon. For the moment, try downgrading to `nodebb-plugin-calendar@1.0.0-alpha.7`

**Comment by ImperatorTheo** [comment]
Confirm this bug... the latest version dont work.

**Comment by pitaj** [comment]
Merging this into #58

**Comment by jasperSpeicher** [comment]
Same issue as OP.

nodebb@1.5.3
nodebb-plugin-calendar@1.0.0-alpha.41
Chrome 62.0.3202.94 
OSX

No errors related to this in log file as far as i can tell, none in the browser console either.
Any help you can offer is greatly appreciated.

**Comment by pitaj** [comment]
@jasperSpeicher the latest version isn't compatible with NodeBB 1.5.3. Either upgrade NodeBB to 1.7.x or use an older version of this plugin.
