### ISSUE TITLE
Display calendar on forums

### ISSUE THREAD

**Issue by antoine-pous** [pitaj/nodebb-plugin-calendar#65]
Hi,

can you add the possibility to manage events from ACP and only display the calendar on the specified pages?

**Comment by pitaj** [comment]
Can you give an example?

**Comment by antoine-pous** [comment]
I would like add the calendar as widget on the pages i want. See in `Extend => Widgets`.

Currently events are cool, but display a global calendar wich contain all events would be awesome.

**Comment by pitaj** [comment]
Well there is a calendar page at `/calendar`. It's not a widget because it's a pretty heavy resource.
