### ISSUE TITLE
Invalid group name error while assigning privileges in category view 

### ISSUE THREAD

**Issue by archprateek** [pitaj/nodebb-plugin-calendar#67]
On version 1.4.2, I get the following error while assigning privileges in category view

27/1 15:34:04 [18726] - [31merror[39m: [groups.join] Could not create new hidden group: invalid-group-name

**Comment by insuusvenerati** [comment]
On 1.4.5 with the same error. Something is wrong with my test installation so i'm not able to provide logs unfortunately. The only thing in my /logs is a blank output.log

**Comment by pitaj** [comment]
It's a known issue. I haven't had time to update the a

**Comment by evoixmr** [comment]
Issue still exist on v1.5.0

**Comment by pitaj** [comment]
@evoixmr can you confirm that this error still occurs when assigning privileges to individual users?

**Comment by evoixmr** [comment]
I would hate to add user privileges, as I do not think it's reversible in nodebb. Once added it's either on or off.

**Comment by pitaj** [comment]
Privileges are additive so user privileges won't override group ones

**Comment by evoixmr** [comment]
All registered users are also getting "Error, You do not have enough privileges for this action."
