### ISSUE TITLE
Not enough privileges

### ISSUE THREAD

**Issue by SiZiGee** [pitaj/nodebb-plugin-calendar#69]
![image](https://cloud.githubusercontent.com/assets/26670492/25594729/2398fe2a-2ec2-11e7-813b-0386b4a485f7.png)

so far everything works... besides being able to click on yes/no/maybe...

what am I missing?

**Comment by pitaj** [comment]
What version of NodeBB? Any errors in the NodeBB log?

**Comment by SiZiGee** [comment]
I got the latest version (v1.4.6) and my logging seems all screwed up, but that is a separate issue (which looks like won't be helping this issue)

    at Pool.<anonymous> (/opt/nodebb/node_modules/mongodb-core/lib/topologies/server.js:327:35)
    at emitOne (events.js:96:13)
    at Pool.emit (events.js:188:7)
    at Connection.<anonymous> (/opt/nodebb/node_modules/mongodb-core/lib/connection/pool.js:274:12)
    at Connection.g (events.js:291:16)
    at emitTwo (events.js:106:13)
    at Connection.emit (events.js:191:7)
    at Socket.<anonymous> (/opt/nodebb/node_modules/mongodb-core/lib/connection/connection.js:177:49)
    at Socket.g (events.js:291:16)
    at emitOne (events.js:96:13)

**Comment by pitaj** [comment]
Um that doesn't appear to be the full error. Can you maybe grab a few more lines above that if possible?

**Comment by SiZiGee** [comment]
I ran ./nodebb log  and clicked yes on my test event to see what it it shows... nothing else showed up

**Comment by SiZiGee** [comment]
Any possible guesses as to why I (as an admin) do not have enough rights to respond to a calendar event?

**Comment by SiZiGee** [comment]
No update?

**Comment by pitaj** [comment]
Sorry man I haven't had time to look into this yet.

**Comment by SiZiGee** [comment]
not a problem. But what do you think the problem could be?  Even a rough guess, as to where to look might help.  Its a useful plugin, but I am keeping it disabled for now and troubleshooting where I can

**Comment by pitaj** [comment]
I think it's related to an invalid privilege name but I'm unsure.

**Comment by SiZiGee** [comment]
I will try with a normal user account and see what happens

**Comment by SiZiGee** [comment]
interesting... with a normal user, it doesn't load, just hangs there
![image](https://cloud.githubusercontent.com/assets/26670492/25888868/0bfd903a-3568-11e7-8f45-782effe4aa4f.png)

**Comment by pitaj** [comment]
It's probably crashing NodeBB of you check in your logs.

**Comment by SiZiGee** [comment]
I did ./nodebb /build  (its getting annoying now, my other forum I don't have to do this.) and I can see it as the normal user, but I cant create any calendar appointments (button is missing) as the user and I cannot accept/decline/maybe on the test one (same error)

**Comment by SiZiGee** [comment]
so I can count this as broken in my instance and remove it from my forum?

seeing as you closed this issue

**Comment by pitaj** [comment]
There are new versions released now. Check here for more information: https://community.nodebb.org/post/60214

**Comment by pitaj** [comment]
If that doesn't resolve your issue then I will reopen this issue.

**Comment by SiZiGee** [comment]
okey dokey.  I will install the latest version. Is it fine to update it? or should I rather remove the current version and then install the latest one?

**Comment by pitaj** [comment]
Just update it. Removing and installing won't do anything special.

**Comment by SiZiGee** [comment]
Awesome. that worked.

Thanks for that :)
