### ISSUE TITLE
Events to not show up in /calendar

### ISSUE THREAD

**Issue by pejuaxel** [pitaj/nodebb-plugin-calendar#72]
See http://forum.assautsurlempire.fr/calendar for example. I have created a single test event on http://forum.assautsurlempire.fr/topic/1134/test-calendrier.

The /calendar page shows up some momentjs warnings related to date format and locale. I'm using a France region based OS, although I haven't managed to get events to show up by changing my system locale.

**Comment by pitaj** [comment]
Are you using redis?

**Comment by pejuaxel** [comment]
Yes

**Comment by pejuaxel** [comment]
Events still do not show up, but this commit fixed errors I had coming from fr.js. I still have some warnings though:

![0_1496207704189_Capture d’écran 2017-05-31 à 07.14.29.png](https://i.imgur.com/8pi8Q2A.png)

**Comment by pitaj** [comment]
The first warning I can't really avoid. Then second warning will be fixed along with this issue.

**Comment by pejuaxel** [comment]
I confirm that's fixed ! :)
