### ISSUE TITLE
Date not formatted in event window on /calendar

### ISSUE THREAD

**Issue by pejuaxel** [pitaj/nodebb-plugin-calendar#74]
On /calendar, when clicking on an event, the date is not correctly displayed.

<img width="584" alt="capture d ecran 2017-05-31 a 12 59 22" src="https://cloud.githubusercontent.com/assets/352768/26629043/0172afd4-4601-11e7-92f0-518c43c3554d.png">

**Comment by pitaj** [comment]
Are there any errors in the console?
