### ISSUE TITLE
Calendar doesn't show up on Chrome

### ISSUE THREAD

**Issue by pejuaxel** [pitaj/nodebb-plugin-calendar#77]
The calendar will not show up on Chrome (58.0.3029.110 (64-bit) on macOS) whereas it displays correctly on Safari.

<img width="883" alt="capture d ecran 2017-06-01 a 09 27 40" src="https://cloud.githubusercontent.com/assets/352768/26669020/951a5fe2-46ac-11e7-9201-b5f3640991ae.png">

**Comment by pitaj** [comment]
Can you try running 

    ./nodebb build && ./nodebb restart

On your server?

**Comment by pejuaxel** [comment]
Just done, still nothing.

**Comment by pitaj** [comment]
Have you tried clearing your cache?

**Comment by pejuaxel** [comment]
That did it, thanks. So not a bug :)
