### ISSUE TITLE
Calendar not translated in correct language

### ISSUE THREAD

**Issue by pejuaxel** [pitaj/nodebb-plugin-calendar#78]
The elements of the calendar plugin always show up in English, while the "fullcalendar" elements are correctly translated.

**Comment by pitaj** [comment]
Most likely because there are not translations in your shed language so it's using the fallback.

**Comment by pejuaxel** [comment]
I'm trying in French which is apparently provided: https://github.com/pitaj/nodebb-plugin-calendar/blob/1.0.x/public/languages/fr_FR/calendar.json

I've tried switching my user language to italian, german and russian but the text still shows up in English.

**Comment by pitaj** [comment]
This is due to NodeBB/NodeBB#5727
