### ISSUE TITLE
Add support for list views in /calendar

### ISSUE THREAD

**Issue by pejuaxel** [pitaj/nodebb-plugin-calendar#83]
Fullcalendar supports list views (https://fullcalendar.io/docs/views/Available_Views/). It would be nice to choose which views are available in /calendar via a setting in ACP.

I would be interested in listMonth and listYear but I guess that's a custom preference according to the community.

**Comment by Terra-F** [comment]
Yes! Our community forum would very much appreciate a list view.

**Comment by kevinoost** [comment]
Would be very cool, indeed.

**Comment by pitaj** [comment]
Check out `nodebb-plugin-calendar@1.0.0-alpha.46`
