### ISSUE TITLE
Is this behaviour right?

### ISSUE THREAD

**Issue by Fank** [pitaj/nodebb-plugin-calendar#87]
The post https://forum.fankserver.com/topic/16/test

But the calander should not show this or?

https://forum.fankserver.com/calendar

**Comment by Fank** [comment]
Btw check next month

**Comment by Fank** [comment]
Ok, it looks like we need a "logical" restriction, because the event duration is longer than the repeat interval, so it stacks.
I'm not sure if you want this as an option to disable it, or hardcoded.
But if this will be an option it should be enabled by default.

**Comment by pitaj** [comment]
Neither of those links is working for me. Anyways, for the topic at hand. 

I don't see why a repeating event should be unable to overlap with itself. Adding special logic to avoid something that doesn't seem to cause any real issues and also is fairly easily avoidable on the user's end doesn't seem worth it.

**Comment by pitaj** [comment]
Neither of those links is working for me. Anyways, for the topic at hand. 

I don't see why a repeating event should be unable to overlap with itself. Adding special logic to avoid something that doesn't seem to cause any real issues and also is fairly easily avoidable on the user's end doesn't seem worth it.

**Comment by Fank** [comment]
Ok it was just a behaviour queation
