### ISSUE TITLE
Events have -1 day

### ISSUE THREAD

**Issue by Fank** [pitaj/nodebb-plugin-calendar#89]
A Event on 28th will open the event in day 27th

socketlog:
```
425["plugins.calendar.getEventsByDate",{"startDate":1496016000000,"endDate":1499644800000}]	
```
![image](https://user-images.githubusercontent.com/1900106/27659923-7acb0736-5c55-11e7-8db9-bc536affc229.png)

![image](https://user-images.githubusercontent.com/1900106/27659900-64760ee0-5c55-11e7-8d9e-442de6c8ffca.png)

Date in calander: OK
Date in panel: OK
Date in url: NOT OK
Date in input: NOT OK
Also the responses will be for 27th not 28th, because of the wrong date in input.

**Comment by pitaj** [comment]
Hmmm.... does this always occur, or only with allday events?

**Comment by Fank** [comment]
Only tested with allday events will validate tomorrow.

**Comment by pitaj** [comment]
Can you provide the event text that's placed in the composer? That could help me reproduce this.

**Comment by Fank** [comment]
I think `[event][name]Asdddccf[/name][allday]true[/allday][startDate]1498860000000[/startDate][endDate]1498946399999[/endDate][reminders][][/reminders][location][/location][description][/description][mandatory]false[/mandatory][repeats]{"every":{"day":true},"endDate":null}[/repeats][/event]` can only test @home

**Comment by pitaj** [comment]
I've identified the cause of this: when the server and client are on sufficiently different timezones, their calculation of the event day corresponding to the certain occurrence of a repeating event will differ. I plan on fixing this via always calculating the `day` based on UTC.

**Comment by gtfr** [comment]
@pitaj: I think the problem is in this line:
https://github.com/pitaj/nodebb-plugin-calendar/blob/1.0.x/src/lib/repetition.js#L149

`day: (new Date(date)).toISOString().split('T')[0]`

For full day events, this will be the previous day if you live in "negative" timezone (e.g. UTC-2)!

I could solve this by:
`day: new Date(date - (new Date(date).getTimezoneOffset()) * 60000).toISOString().split('T')[0]`

This should correct the timezone difference.

**Comment by gtfr** [comment]
@pitaj There is another occurence of such a call in:
https://github.com/pitaj/nodebb-plugin-calendar/blob/1.0.x/src/client/responses.js#L149

```
  $(document.body).on('change dp.change', '.plugin-calendar-event-responses-day input', (e) => {
    const input = $(e.target);
    const day = input
      .data('DateTimePicker').date()
      .toISOString()
      .split('T')[0];
```

This leads to a -1 day offset for all repeated events in the database 😞 (in my timezone).

**Comment by pitaj** [comment]
Yeah it certainly looks like that is the culprit. Thanks for investigating, I'll see if I can fix it in the coming days.
