### ISSUE TITLE
webpackJsonp is not defined

### ISSUE THREAD

**Issue by ToeiRei** [pitaj/nodebb-plugin-calendar#91]
My calendar doesn't show up. Found that in the console:

```Uncaught ReferenceError: webpackJsonp is not defined
    at plugins/nodebb-plugin-calendar/bundles/calendar.js?v=j3ioevjc3mc:1```

**Comment by pitaj** [comment]
Run `./nodebb build` again. For some reason, sometimes this error occurs and sometimes it doesn't.

**Comment by ToeiRei** [comment]
I could get to some reproduction / solution.

If you do something with plugins, the calendar breaks
disable / reenable and things look fine again

**Comment by pitaj** [comment]
Hmmm... it could be the plugin activation order maybe

**Comment by ToeiRei** [comment]
everytime I do something with plugins the issue occurs. `./nodebb build`helps as a workaround.

**Comment by pitaj** [comment]
This was an issue with NodeBB upstream.
