### ISSUE TITLE
Display problem when creating a new event

### ISSUE THREAD

**Issue by spiritax** [pitaj/nodebb-plugin-calendar#92]
They is a display problem when creating a new event, it occur on wide screen.

<img width="866" alt="screen shot 2017-07-21 at 14 48 18" src="https://user-images.githubusercontent.com/10990671/28464213-722a4b60-6e24-11e7-9d94-1e0ee1d297cc.png">

If i reduce the window, the display is fine.

<img width="721" alt="screen shot 2017-07-21 at 14 47 43" src="https://user-images.githubusercontent.com/10990671/28464222-7f7fbeda-6e24-11e7-82b9-0c9c122673b0.png">

**Comment by pitaj** [comment]
What browser?

**Comment by Fank** [comment]
Tested Chrome and Firefox both worked fine.

**Comment by spiritax** [comment]
I'm on chrome, macOS Sierra.

**Comment by pitaj** [comment]
What Chrome version?

**Comment by spiritax** [comment]
Latest : Version 59.0.3071.115 (Official Build) (64-bit)

**Comment by pitaj** [comment]
Have you tried running `./nodebb build`? Is your calendar public so I can see for myself? What theme are you on?

**Comment by spiritax** [comment]
Alredy tried the ./nodebb build and it still have the bug.

I'm using the default theme : Persona

i'll send you a email with the url and some credentials in a few min.

**Comment by pitaj** [comment]
I think this is because of another plugin's styles. I think I can fix it by changing the styles on those elements or by removing a class. You can fix it with this custom CSS:

```css
.plugin-calendar-event-editor-date {
  width: auto;
}
```

**Comment by spiritax** [comment]
Thanks, i'll try.

do you happen to know if it's a other plugin that make moment not showing correctly on the main page?

<img width="1167" alt="screen shot 2017-07-21 at 21 34 12" src="https://user-images.githubusercontent.com/10990671/28479426-a4a356a8-6e5c-11e7-944a-723855122724.png">

can i disable the access i made for you?

**Comment by Fank** [comment]
@spiritax #84

**Comment by pitaj** [comment]
Go ahead and disable access. I'm done. as @Fank just said, that other issue is already documented elsewhere.

**Comment by spiritax** [comment]
Thanks for the help.
