### ISSUE TITLE
Opening event info dialog moves calendar to the left

### ISSUE THREAD

**Issue by Fank** [pitaj/nodebb-plugin-calendar#95]
Before opening:
![image](https://user-images.githubusercontent.com/1900106/28490145-d764b4e4-6ed2-11e7-9cea-76334417cd1e.png)
![image](https://user-images.githubusercontent.com/1900106/28490147-dd52993e-6ed2-11e7-8f26-640b04615f4d.png)

After opening
![image](https://user-images.githubusercontent.com/1900106/28490149-e8342e9e-6ed2-11e7-9d68-a2dce91bae21.png)
![image](https://user-images.githubusercontent.com/1900106/28490150-efb6f25a-6ed2-11e7-87f3-ed19ae2bc8be.png)

The `padding-right: 15px;` will be added to both, dialog and body tag. But it should not be added to the body tag.

**Comment by pitaj** [comment]
Pretty sure this is just how bootstrap modals behave.
