### ISSUE TITLE
List view in responses

### ISSUE THREAD

**Issue by kevinoost** [pitaj/nodebb-plugin-calendar#99]
Would be awesome to have a name-list view of responses, instead of user-avatars.
In addition, a total count for each Yes/No/Maybe.

As discussed [here](https://community.nodebb.org/topic/4401/nodebb-plugin-calendar-fully-featured-calendar-plugin-for-nodebb-testers-needed/403).

**Comment by pitaj** [comment]
You can now override the [response list template](https://github.com/pitaj/nodebb-plugin-calendar/blob/1.0.x/public/templates/partials/calendar/event/response-list.tpl) to accomplish what you want to see.
